### ISSUE TITLE
[docs] Give more information on README.md to run the solution.

### ISSUE THREAD

**Issue by eecopa** [bckpropagation/fast_service#2]
### Documentation so other members of the team can run the project on their machines.

**Incomplete documentation**
As mentioned in the title, the documentation inside README.md file is incomplete. Please, give a brief explanation on how to set up the environment or how to run the project.

**Write a better README.md**
I would suggest to:
* Give details on how to set up the environment
* Give details on how to run the project

**Comment by fwxs** [comment]
Detailed data on how to setup and execute the server, was added to README.md file on PR #5.
